spring.application.name=Backend

# LOCAL PostgreSQL
#spring.datasource.url=jdbc:postgresql://localhost:5432/sgra?currentSchema=seguridad,reforzamiento,academico,general,public
spring.datasource.url=jdbc:postgresql://sgra-postgres.postgres.database.azure.com:5432/SGRA-SIN-DATOS?sslmode=require&currentSchema=seguridad,reforzamiento,academico,general,public
spring.datasource.username=sgra_app
spring.datasource.password=#012345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.orm.jdbc.bind=trace

server.port=8080

# Activar profile local para desarrollo
spring.profiles.active=local

server.servlet.session.timeout=30m
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=lax

# Master key placeholder (sobreescrito en application-local.properties)
sgra.master-key=${SGRA_MASTER_KEY:}

# Configuracion del pool de conexiones dinamico por usuario
sgra.pool.max-size-per-user=3
sgra.pool.idle-timeout-minutes=10
sgra.pool.max-lifetime-minutes=30
sgra.pool.cleanup-interval-minutes=5

# Groq Cloud AI Configuration
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.api.key=${GROQ_API_KEY:}
groq.model=llama-3.3-70b-versatile
groq.max-tokens=4096
groq.temperature=0.1
groq.timeout-seconds=10

# Configuracion de Azure Storage
spring.cloud.azure.storage.blob.connection-string=DefaultEndpointsProtocol=https;AccountName=sgrastorage2026;AccountKey=yNNbt2ImfDaS9wIxT0VwlOR/Zi0RdIgs8iD45maSrBmj1F4Dmk3W5CBPgGSAliCh5ri3pINk8QmV+ASt9nznLQ==;EndpointSuffix=core.windows.net
spring.cloud.azure.storage.blob.container-name=archivos-sgra
spring.servlet.multipart.max-file-size = 10MB
spring.servlet.multipart.max-request-size = 10MB